name: nama_app

description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.7
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  uuid: ^4.2.1
  mailer: ^6.4.1
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  http: ^1.3.0
  cached_network_image: ^3.3.1
  permission_handler: ^11.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - lib/Image/logonama.jpg
  - lib/Image/logo.jpg
  - lib/Image/nen.png

  
